apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yg6z8fnh2-python 
  janus-idp.io/tekton: yg6z8fnh2-python
  backstage.io/kubernetes-id: yg6z8fnh2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yg6z8fnh2-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml