apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yg6z8fnh2-python
  janus-idp.io/tekton: yg6z8fnh2-python
  backstage.io/kubernetes-id: yg6z8fnh2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yg6z8fnh2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
