apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yg6z8fnh2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:5e7af35c79a10f37687c9d484dfff055b04d5bb4@sha256:00bed5efb85cca5728e9ed7173460d749c5a9cc220ed106dddda8f3b58b64cde
          name: container-image
